### PR TITLE
Added social buttons to blog posts and some other pages

### PR DESCRIPTION
**Pull request by DeckOfPandas**

### CODE REVIEW

**Comment by DeckOfPandas** [comment]
The fourth commit here should have -m "Wired up twitter button"

**Comment by DeckOfPandas** [comment]
This facebook URL doesn't work for me ("Sorry this facebook plugin is not available right now"):
http://www.facebook.com/sharer.php?u={{site.url}}{{page.url}}

Mouseover on the link displays the URL we want though :/

**Comment by mattstibbs** [comment]
Lookgs good to me

**Comment by DeckOfPandas** [comment]
Just going to merge then see where we are!

**Pull request merged**
