### PR TITLE
NHS Hack Day Dot Com v 3.0

### PR DESCRIPTION
**Pull request by davidmiller**
This PR of entirely appropriate size contains an almost complete re-write of the NHS HackDay Website.

All of the thanks to @fredkingham @DeckOfPandas @pacharanero for that ! :D

A deployed version of the results of this PR is viewable at http://newnhshackdaysite.github.io/

There are still a few rough edges here and there, but this is IMHO a deployable improvement to the existing http://nhshackday.com/

It would be super if we were able to move to a world where we were working on the live site and improvements were made as small individual PRs to the actual website here!

Paging @DeckOfPandas @rossjones @pacharanero @fredkingham @doismellburning for someone to agree enough to merge

### CODE REVIEW

**Comment by rossjones** [comment]
Duplicate entry for Manchester at http://newnhshackdaysite.github.io/events/ :(

**Comment by davidmiller** [comment]
Great spot @rossjones - no longer duplicated :)

**Comment by doismellburning** [comment]
yolomerge

**Comment by doismellburning** [comment]
(Seriously, props, looks totes awes)

**Comment by pacharanero** [comment]
There is something odd going on with the code which autogenerates that list
of previous events.

Yesterday I had inexplicably missing 'London 2015' and then next time I
looked it was 'Cardiff 2015' that was missing. Now we have 2 Manchesters.

I wondered if the missing ones were something to do with the YAML front
matter being invalid (easy to make YAML invalid with a formatting mistake
in the whitespace) but I don't know how that would explain 2 Manchesters.
One Manchester is enough for anyone.

M

**Comment by pacharanero** [comment]
Other than that glitch (which we can fix on the live site): Merge+1

M

**Comment by davidmiller** [comment]
@pacharanero There were just two manchester posts: 

https://github.com/nhshackday/nhshackday.github.io/tree/cf220fd6a845ec70265f040aa9f978aa1da18858/_posts/events

**Comment by pacharanero** [comment]
OK

M

**Comment by DeckOfPandas** [comment]
Yep, merge++
Am excite!

**Pull request merged**
