### PR TITLE
corrected name of BCS to 'BCS, The Chartered Institute for IT'

### PR DESCRIPTION
**Pull request by pacharanero**

### CODE REVIEW

**Comment by pacharanero** [comment]
@davidmiller @DeckOfPandas :wave:

**Comment by davidmiller** [comment]
Perhaps we could whip up an event page as well ?

**Comment by pacharanero** [comment]
Yes but probably not today
M

**Comment by DeckOfPandas** [comment]
Urgh, this now conflicts...over one line
@pacharanero :bats-eyelashes: ?

**Comment by pacharanero** [comment]
this PR can be deprecated, the BCS are now no longer on our index.html

**Pull request closed without merging**
