### PR TITLE
Some colors and layouts for blocks of text etc

### PR DESCRIPTION
**Pull request by DeckOfPandas**
Jam = the bit between the bread

### CODE REVIEW

**Comment by DeckOfPandas** [comment]
The wonderful @londonlime has offered to replace the above with a palette that actually looks good! I'll leave the PR open, and will add to it turning the colors into variables in the first instance

**Comment by Londonlime** [comment]
first stab at this. might have obvious holes! the blue was an afterthought in case the lime is too vivid as a background. 
screen shot 2018-01-24 at 09 46 05

**Comment by DeckOfPandas** [comment]
Thanks so much @Londonlime :):):):)

Yes, changing the colours is straightforward (and I'm about to make it more so now).

**Comment by DeckOfPandas** [comment]
Closing this for now pending PR from @blu3id, after which I'll re-apply

**Pull request closed without merging**
