### PR TITLE
fix FB sharing URL

### PR DESCRIPTION
**Pull request by blu3id**
This should work.... at least it does locally

### CODE REVIEW

**Comment by DeckOfPandas** [comment]
I still see this:
screen shot 2018-01-22 at 13 04 55

**Comment by DeckOfPandas** [comment]
:(

Could it be my browser/setup?

**Comment by DeckOfPandas** [comment]
Same issue when I turn adblock off...

**Comment by blu3id** [comment]
the issue is you testing on localhost!

**Comment by DeckOfPandas** [comment]
Why does facebook care what the URL is that I want to share?

(I don't doubt that you're right, I just don't understand)

**Comment by blu3id** [comment]
As I said protection of their local infrastructure - basically no localhost URL and they don't care. Also protection of their users - no phishing URLs etc.

**Comment by blu3id** [comment]
So basically this will work on the live site, or local staging if you have a non localhost URL

**Comment by mattstibbs** [comment]
Works for me if I copy the link and paste in nhshackday.com into the URL

**Comment by DeckOfPandas** [comment]
I just tested this on one of the blog post pages, and actually posted (in a private message), but the URL that was shared was just nhshackday.com rather than the page I shared from

**Comment by DeckOfPandas** [comment]
Well if you two are happy then I'll merge!

**Comment by blu3id** [comment]
Looks to be working on the live site for me.

**Pull request merged**
