### PR TITLE
Automatic anchor links

### PR DESCRIPTION
**Pull request by doismellburning**
Note, this changes markdown engine. I do not know anything about Ruby Markdown engines, I've just cargoculted over what I use for my own Jekyll stuff. I recommend talking to someone who may actually grok markdown engines - afaict I haven't broken anything obvious, but yeah, computers

### CODE REVIEW

**Comment by davidmiller** [comment]
@doismellburning Is it going to continue to deploy from GHPages ? 

Are you sure? ;)

**Comment by doismellburning** [comment]
Ah, had forgotten about that...

**Comment by doismellburning** [comment]
According to https://pages.github.com/versions/, rdiscount is present!

**Comment by doismellburning** [comment]
I'd bet a beer on it (and if you let me know when you're about to merge, I'm happy to do any necessary git-fiddling to revert if necessary ;))

**Pull request merged**
