### PR TITLE
Site Cleanup

### PR DESCRIPTION
**Pull request by blu3id**
Shamelessly stolen from the `README.md`:
>Welcome to the _new_, new NHS Hack Day website. This is a rebuild of the older [Jekyll](https://jekyllrb.com/) site that was last refreshed in ?January 2016. There is little that has changed from a design perspective (there has been a metaphorical "lick of paint" for more consistent styling, better responsive/mobile design and some changes to how projects are displayed) but the underlying structure, templates and CSS have undergone a complete rebuild.

This PR supersedes @DeckOfPandas #232 because of merging issues and :waves-hands: magic staging only works from PRs from branches on the repository.

This **should** be a drop-in replacement for the current site i.e stuff that is accessible and linked on the current site should have been copied over. However **many eyes** checking would be appreciated, the biggest risks for broken bits and changes are:
- Due to the restructuring it is possible that some project info and links may have been lost or broken
- Sponsors may be missing
- Whole pages may be missing if they were only linked from one place
- The header is lime green (it has grown on me)
- Some content has been edited slightly e.g site footer

If all works as intended there should be a link to a staging version of the site in the comments below.

### CODE REVIEW

**Comment by davidmiller** [comment]
The nine million files you've changed are too much for Github PR review :) 

```
{% assign current_time = site.time | date: "%s" | to_integer %}
{% assign sorted = site.events | sort: 'date' | reverse %}
{% for post in sorted %}
    {% assign start = post.date | date: "%s" | plus: 86400 | to_integer %}
    {% unless start >= current_time %}
```

@blu3id can you talk me through the plus 24hours there....
It's supposed to appear in previous at midnight on the Sunday ?

**Comment by davidmiller** [comment]
(My apologies - closure was clicking close and comment instead of comment)

**Comment by blu3id** [comment]
Yes this is a dirty, filthy hatchet job of a hack on Jekyll on that page, which unsurprisingly you have found an error in despite my testing. This is because of edge cases it should probably be adding x2 days (172800). Basically I need to fix this - I cant directly use post.end_date because this can sometimes be text in upcoming event.... so we can either change to 172800 which assumes all Hackdays are 2 days long? or I can pile further hatchet job logic in....

**Comment by davidmiller** [comment]
From @blu3id in a thread elsewhere:

> And obv. this display logic is at site build time anyway so unless the site is updated over the weekend nothing happens.

You know, I had in fact forgotten this. 
Given that I'd be very tempted to just simplify the whole thing and have it be 'upcoming' or 'past' immediately that now is > start_date

**Pull request merged**
