### PR TITLE
Graphics

### PR DESCRIPTION
**Pull request by DeckOfPandas**
- Included Ayesha's gorgeous new images
- Tidied up the table on the webpage
- Moved unused files to old/

### CODE REVIEW

**Comment by DeckOfPandas** [comment]
This should all be okay, but a sanity check would be great please @davidmiller or @pacharanero etc

**Comment by davidmiller** [comment]
Hi @DeckOfPandas looks good, but I think we already have a London event page :)

http://nhshackday.com/previous/events/2016/05/london/

**Comment by DeckOfPandas** [comment]
@davidmiller ...that was a mistake. Will fetch upstream harder...

**Comment by DeckOfPandas** [comment]
I tried again here:
https://github.com/nhshackday/nhshackday.github.io/pull/192

**Pull request closed without merging**
